source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby "~> 3.3.0"

gem "rake", "~> 13.0"
gem "aws-sdk-s3", "~> 1.0"
gem "rexml"

group :development, :test do
  gem "rspec", "~> 3.0"
  gem "rspec-its"
  gem "rspec-parameterized"
  gem "rspec-mocks"
end
